# Generated by Django 3.1.7 on 2021-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='drfmodel',
            name='is_gey',
            field=models.BooleanField(default=False),
        ),
    ]
