# Generated by Django 3.1.7 on 2021-04-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0002_auto_20210408_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfmodel',
            name='age',
            field=models.IntegerField(unique=True),
        ),
    ]
